# config/packages/security.yaml

security:
    providers:
        in_memory:
            memory: ~

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            provider: in_memory
            # Ajoutez vos configurations de pare-feu ici
